### ISSUE TITLE
using callable instead of closure

### ISSUE THREAD

**Issue by nyamsprod** [bocharsky-bw/Arrayzy#16]
Since this package minimum requirement is PHP 5.4 you should update your code to typehint against `callable` instead of `closure` as this would [broaden its usability](http://stackoverflow.com/a/29730810).

**Comment by bocharsky-bw** [comment]
@nyamsprod Yes, you're right here. We definitely should use `callable`. Thank you!

Do you want to create a PR for it?

**Comment by nyamsprod** [comment]
@bocharsky-bw sorry I can't I have my hand full of projects right now but it's a quick fix to apply IMHO

**Comment by bocharsky-bw** [comment]
@nyamsprod OK, no problem, I just asked. I'll do it. Anyway, thanks!

**Comment by bocharsky-bw** [comment]
Resolve in https://github.com/bocharsky-bw/Arrayzy/commit/52dcaf0c057cc4173f209cdde95058b75585f210
