### ISSUE TITLE
Refactor constructor with variadic arguments

### ISSUE THREAD

**Issue by bocharsky-bw** [bocharsky-bw/Arrayzy#19]
This **Hall_of_Famer** idea from his [comment](https://www.reddit.com/r/PHP/comments/3nysjn/the_wrapper_for_all_php_internal_builtin_array/cvssoxc) on reddit.com.

I see that you create your array objects by accepting a parameter of PHP array. I wonder though, why dont you just make the constructor and other factory methods variadic? So instead of this:

``` php
$immArr = new ImmutableArray([1, 2, 3]);
$mutArr = new MutableArray([1, 2, 3]);
```

You now have:

``` php
$immArr = new ImmutableArray(1, 2, 3);
$mutArr = new MutableArray(1, 2, 3);
```

This way the API looks a lot cleaner to me. Also I think it is better to separate arrays from dictionaries/hash tables. So it would be better to have separate classes that handle numeric and associative array differently, than to have one array class that does both.

**Comment by bocharsky-bw** [comment]
Cons: Not being able to leave a trailing comma would be annoying though

**Comment by m1** [comment]
Have you thought about how you would do associative arrays using the new syntax?

**Comment by bocharsky-bw** [comment]
@m1 It's one more cons again. Another good point!

**Comment by pmysiak** [comment]
What about new syntax as follow:

$a = new Arrayzy\ImmutableArray([1, 2, 3], 4, 5, 'a', 'b', ['a' => 'b']);

Result array will be smart merged.

i could create PR.

**Comment by bocharsky-bw** [comment]
@pmysiak Well, I don't like this :-1: .
I prefer to keep things simple and use it as is (use array as first and single argument) here.

**Comment by m1** [comment]
@pmysiak Yeah not a fan of that syntax either.

**Comment by bocharsky-bw** [comment]
So I don't see any advantages of variadic arguments yet. We just get some problems with it
