### ISSUE TITLE
Immutable array could be modified with some methods

### ISSUE THREAD

**Issue by bocharsky-bw** [bocharsky-bw/Arrayzy#21]
The original `ImmutableArray` object should NOT be changed with `push()`, `unshift()`, `shift()` and `pop` methods. It should return new object with this changes.

Thanks guys from reddit.com [discussion](https://www.reddit.com/r/PHP/comments/3nysjn/the_wrapper_for_all_php_internal_builtin_array/cvsksxm).

**Comment by bocharsky-bw** [comment]
Resolve in https://github.com/bocharsky-bw/Arrayzy/pull/24

**Comment by nyamsprod** [comment]
@bocharsky-bw the bug is still present even with this change because your mutable and immutable object share the **same** interface You must create two distinct interfaces any other solutions is not acceptable consider this following code:

``` php
function change(Arrayzy\Interfaces\ModifiableInterface $arr)
{
     return $arr->push();
}
```

Using the current codebase depending on the object given the result is quite different!!  `ImmutableArray::push()` and `MutableArray::push()` **share the same public API signature but not the same API**  as explain in the Reddit thread a good example is how the `DateTimeInterface` is built in PHP.
IMHO you should stick to either a Immutable or a Mutable representation. Doing both will always lead to problems and workarounds.

**Comment by bocharsky-bw** [comment]
@nyamsprod Thank you to point it again!

So, as I understand, for example, such interfaces like the [ConvertibleInterface](https://github.com/bocharsky-bw/Arrayzy/blob/master/src/Interfaces/ConvertibleInterface.php) could be the same for both `ImmutableArray` and `MutableArray` classes, because these methods are simply returns a scalar values and don't directly change the array.

But for [SortableInterface](https://github.com/bocharsky-bw/Arrayzy/blob/master/src/Interfaces/SortableInterface.php) or [ModifiableInterface](https://github.com/bocharsky-bw/Arrayzy/blob/master/src/Interfaces/ModifiableInterface.php) we should create a separate interfaces like `ImmutableSortableInterface` and `MutableSortableInterface` to keep the same methods signature but different behaviour.

Right?

P.S. Do you have any example of an open source library with such implementation you described?

**Comment by nyamsprod** [comment]
Yes that's it. only getter methods which do not change the underlying data structure can be share between both implementations with the same interface. Any other method can not be shared through the same interface.

That's why I'm saying that for maintainability it is easier to choose which implementation you want and stick with it. I run into this same problem with the League\Url v3 library and I choose in v4 to discard any mutable object. Now the code and its usage are simplified. I'm not suggesting you to go full immutable, but it would be better if you were more opinionated on this library and choose which implementation suit you best and stick with it. Having both in the same package is a recipe for problems.

my 2 cents.

**Comment by bocharsky-bw** [comment]
@nyamsprod Now I see your point.

I was inspired with [Stringy](https://github.com/danielstjules/Stringy) and Doctrine's [ArrayCollection](https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ArrayCollection.php) when create this lib. Now I see that Stringy are fully _immutable_. BTW, ArrayCollection are _immutable_ too for some methods, but not for all. So I'm more inclined to use **immutable** objects and get rid of _mutable_ one. But I don't sure yet because mutable objects are interesting too IMO.

I'm also wondering what do you suggest me to use: `immutable` ot `mutable` objects for this library?

**Comment by nyamsprod** [comment]
@bocharsky-bw this boils down to how you will use your object for. There's no right or wrong way to do it ? See this [reddit thread](https://www.reddit.com/r/PHP/comments/3itwi7/why_do_functions_like_array_push_or_usort/) for insight of why current php methods work the way they do. Then think of your use cases. Arrays can be use:
- for collections;
- for data structures;
- for so many things;

I would firsrt identify what I want then build a object around it not the other way as this would lead to confusion

**Comment by bocharsky-bw** [comment]
So does it fine to use some mutable and some immutable methods in a single class, in terms of architecture?

**Comment by nyamsprod** [comment]
yes it's fine as long as it is clearly stated in the interface:
- if you call your class `Data` and `Data` has some immutable methods that's fine;
- if you call your class `ImmutableData` and some of its methods are mutable then we have a problem.

**Comment by bocharsky-bw** [comment]
I was thinking a lot on this weekend about this bug and came to the following conclusions.

Currently, `ImmutableArray` has adders and setters in order to add new elements to the array and set/replace exist one respectively. So having it in this class will break the design of immutability as is as I understand. BTW, I don't like idea to create a new instance every time when I add new element to the array. That's why I think I need to reject full immutability for _main_ class of this lib.

Going further, I think we need to get rid of full mutability for _main_ class of this lib too. I consider this library as a wrapper for all PHP built-in array functions, I think I need to follow PHP built in functions design. I mean, that if the `array_merge()` function is _immutable_ and the `array_push()` is mutable - I need to follow this design and make the `merge()` method is immutable and the `push()` one is mutable respectively for main class, and I plan to name this main library's class as **ArrayCollection**.

A bit summary:
- For now, I get rid of current `MutableArray` and `ImmutableArray` classes;
- I create `ArrayCollection` class which is the main class of this lib;
- This (`ArrayCollection`) class have both mutable and immutable methods according to PHP built-in functions behavior.

Lastly, after this big refactoring, we could think about implementation of full immutability/mutablilty that implemented with separate classes, not in the same `ArrayCollection` class, if this features make sense, and we really need it.

P.S. @nyamsprod I'm also wondering your opinion about this.

**Comment by nyamsprod** [comment]
if you are now sure on your goals and want to build an arrayCollection package I have nothing against it. Just make sure that your collection is really not just another collection class like the [illuminate Collection class](https://github.com/illuminate/support/blob/master/Collection.php).

The only question you should ask yourself is having a fully immutable class really needed for a array representation ? IMHO the answer is no

**Comment by ecolinet** [comment]
What's the point with Immutable arrays ? I don't see any use case for them.

For me a component like this one should be very simple with a very minimum set of Interfaces.

**Comment by bocharsky-bw** [comment]
@ecolinet Thanks for your comment. I just used `Immutable` word here to point that some methods (not **all**) in this class return new instance and do not modified current object. It's definitely was an error that **nyamsprod** pointed me and now I doing some code refactoring to fix it.
