### ISSUE TITLE
Tag Version with "find" method included

### ISSUE THREAD

**Issue by th3l0g4n** [bocharsky-bw/Arrayzy#31]
Hi Victor, is it possible that you create a Version where the find method is included? This would be much appreciated.

**Comment by bocharsky-bw** [comment]
Hey, @th3l0g4n , thank you for remind me!
I just released the latest changes as [v0.3.0](https://github.com/bocharsky-bw/Arrayzy/releases/tag/v0.3.0).

**Comment by th3l0g4n** [comment]
Thanks man!

**Comment by bocharsky-bw** [comment]
No problem!
OK, I close this issue.
